### ISSUE TITLE
Layouts - Unit Tests

### ISSUE THREAD

**Issue by ocni-dtu** [Arkitema/arkitema-ui#30]
- arkitemaTable
- paperPage
- paperPageStack

**Comment by ocni-dtu** [comment]
arkitemaCard gives error message:

```
stderr | packages/layout/src/arkitemaCard/arkitemaCard.spec.tsx > CarbonCard > should render carbon card successfully
Warning: ArkitemaCard: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
    at ArkitemaCard (/home/chrk/git/arkitema/arkitema-ui/packages/layout/src/arkitemaCard/arkitemaCard.tsx:14:11)
    at RenderedRoute (/home/chrk/git/arkitema/arkitema-ui/node_modules/react-router/dist/umd/react-router.development.js:540:7)
    at Routes (/home/chrk/git/arkitema/arkitema-ui/node_modules/react-router/dist/umd/react-router.development.js:1131:7)
    at Router (/home/chrk/git/arkitema/arkitema-ui/node_modules/react-router/dist/umd/react-router.development.js:1063:17)
    at MemoryRouter (/home/chrk/git/arkitema/arkitema-ui/node_modules/react-router/dist/umd/react-router.development.js:965:7)

```
